### PR TITLE
PR: Set up FastAPI backend & endpoints with fake database

### PR DESCRIPTION
**Pull request by gyu123987**
Story: #7

### CODE REVIEW

**Review by kevwjin — APPROVED** [review]
LGTM!

**Review by sdcarlson — APPROVED** [review]
lgtm

**Review by kevwjin — APPROVED** [review]
LGTM, again!

**Review by sdcarlson — APPROVED** [review]
lgtm

**Review by sdcarlson — DISMISSED** [review]
lgtm

**Review by kevwjin — APPROVED** [review]
lgtm

**Pull request merged**
